import { useState, useEffect } from "react"
import { Layout } from "../components/Layout"
import Web3Modal from "web3modal"
import { ethers } from "ethers"
import { TabSelector } from "../components/TabSelector"
import Head from 'next/head'


export default function Home() {
  
  


  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
      
      </Layout>
    </div>
  )
}
